### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ashokpatowary** [flemingtonlab/circleVis#3]
Hi @nungerleider

I am having the following error. Can you look into it.  

File "SpliceV", line 608
    *line, attributes = line.split('\t')
    ^
SyntaxError: invalid syntax

**Comment by nungerleider** [comment]
I changed the code a bit - give it a shot now.

**Comment by ashokpatowary** [comment]
@nungerleider 

Thanks its working now. I am having a query regarding the output plot. If I am having a gtf file of full length of the gene/transcript and a bam file where I am having incomplete transcripts; what the output plot will be: for the full length gtf or incomplete transcripts from the bam?

**Comment by nungerleider** [comment]
Exon structure is derived from the gtf file, coverage and splice junction info comes from your bam file. The plot should show which regions of the transcript has coverage and which regions do not.
