### ISSUE TITLE
UnboundLocalError: local variable 'y2' referenced before assignment

### ISSUE THREAD

**Issue by KathFan** [flemingtonlab/circleVis#4]
Hi there,

Trying to run SpliceV to visualise backsplice junctions but I keep getting this particular error:

```
Traceback (most recent call last):
  File "/apps/python/3.7.3/bin/SpliceV", line 1069, in <module>
    main()
  File "/apps/python/3.7.3/bin/SpliceV", line 1038, in main
    plot_circles(ax=ax, coordinates=circle, gene_size=gene_length,y=ybottom + .2 *height, cds_range=cds_range )
  File "/apps/python/3.7.3/bin/SpliceV", line 333, in plot_circles
    draw_backsplice(ax=ax, start=start, stop=stop, y=y1,y2=y2, adjust=num, bezier_offset=.1, gene_size=gene_size)
UnboundLocalError: local variable 'y2' referenced before assignment
```
This is what i run:

`SpliceV -b /star_gWk23_1Aligned.sortedByCoord.out.bam -bsj bsjTestS2.txt -gtf gencode.v21.annotation.gtf -g SMAD2`

The bsj file is currently
`chr18   47865059        47896809        -       10`

I have tried reinstalling SpliceV and the dependencies, Hisat2 and Star files and different genes, but when i try run it with a bsj file, it does not work. The bsj is from a Ciri2 output. I can generate images with splicing, but just not with backsplicing.

Wondering if you've come across this particular error and have any ideas about whats wrong?

Thank you!
Kathy

**Comment by KathFan** [comment]
Also, just tried running it with hg19 as annotation, and it did produce an image - but no backsplicing. It produced the above error when run with hg38.

Cheers.

**Comment by nungerleider** [comment]
Ahh sorry for the delay. Give it a shot now.

Best,

Nate
